import "./globals.css";
import Stairs from './common/Stairs'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Stairs>
        {children}
        </Stairs>
      </body>
    </html>
  );
}
